[workspace]
members = ["physics", "rocket", "utils"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Ben Chater"]
edition = "2021"
license = "MIT"
repository = "https://github.com/melliphera/planetarylander"

[workspace.dependencies]
rand = "0.8"

[profile.profiling]
inherits = "release"
debug = true
opt-level = 3